---
title: Stackbit Azimuth Theme
baseURL: "/"
params:
  palette: orange
  header:
    title: Azimuth
    logo_img: "/v1566485361/azimuth-hugo-forestry/logo_sd5ctx.svg"
    has_nav: true
    menu:
      actions:
      - label: Sign Up
        url: "/signup"
  footer:
    logo_img: images/logo_alt.png
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Company
    has_social: true
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; Stackbit. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
